server:
  port: 10010
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: mail-service # 路由标示，必须唯一
          uri: lb://mail # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/mail/** # 路径断言，判断路径是否是以/mail开头，如果是则符合
        - id: login-service
          uri: lb://login
          predicates:
            - Path=/login/**
      default-filters:
        - AddRequestHeader=Truth,Itcast is freaking awesome!
eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka