server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/library_management_system?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: login
mybatis:
  type-aliases-package: com.nmsl.login.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    cn.itcast: debug
eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka
